language: csharp
mono: none
dotnet: 3.1.100
script:
 - dotnet restore ./src/Cablemodem.sln
 - dotnet build ./src/Cablemodem.sln
 - dotnet test ./src/Infraestructura.Test/Infraestructura.Test.csproj
 - dotnet test ./src/Servicios.Test/Servicios.Test.csproj